name: flutter_ruler
description: "A Flutter package that provides a customizable horizontal and vertical ruler widget for precise measurements input."
version: 0.0.1
homepage: https://github.com/danyalyameen/Flutter-Ruler/

# Environment
environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Assets
flutter:
  # assets:
    # Example for adding assets (uncomment if you have images or other assets)
    # - assets/images/
  
  # Fonts
  # fonts:
    # Example for adding custom fonts (uncomment and add your fonts if needed)
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #       style: italic
